### ISSUE TITLE
Build error on nan_point.h

### ISSUE THREAD

**Issue by halton** [01org/widl-nan#115]
This error should be a regression after merging #114 

https://travis-ci.org/01org/widl-nan/jobs/226802447

```
make: Entering directory `/home/travis/build/01org/widl-nan/test/static-member/build'
  CXX(target) Release/obj.target/widlNanAddon/addon.o
../addon.cpp:3:28: fatal error: gen/nan__point.h: No such file or directory
 #include "gen/nan__point.h"
```
