### PR TITLE
In new version of WebIDL2 parser, the acceptable syntax changed so we…

### LINKED ISSUE #115: Build error on nan_point.h
This error should be a regression after merging #114 

https://travis-ci.org/01org/widl-nan/jobs/226802447

```
make: Entering directory `/home/travis/build/01org/widl-nan/test/static-member/build'
  CXX(target) Release/obj.target/widlNanAddon/addon.o
../addon.cpp:3:28: fatal error: gen/nan__point.h: No such file or directory
 #include "gen/nan__point.h"
```

### PR DESCRIPTION
**Pull request by kenny-y**
… need to do some adaption.

Closes #115

### CODE REVIEW

**Comment by kenny-y** [comment]
Merging since trybot is green...

**Comment by halton** [comment]
Great, and thx
